obstacle_range: 2
raytrace_range: 2
# obstacle_range: 2.5
# raytrace_range: 3.0
# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105
robot_radius: 0.15
inflation_radius: 0.4
cost_scaling_factor: 3.0
map_type: costmap
observation_sources: scan
scan: {data_type: LaserScan, topic: /imagination_laser_scan, marking: true, clearing: true}